version: '3'
services:
  api:
    container_name: api
    build: 
      dockerfile: "Dockerfile"
      context: "execution_environment/api"
    volumes:
      - type: bind
        source: ./execution_environment/api/src
        target: /workspace
    expose:
      - 1323
    command: /bin/bash -c "/workspace/api"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    expose:
      - 8080
    volumes:
      - ./execution_environment/keycloak/dbdata:/opt/keycloak/data # DB情報等が格納されます
    environment:
      KEYCLOAK_ADMIN: admin # 管理ユーザーIDを設定
      KEYCLOAK_ADMIN_PASSWORD: passwd # 管理ユーザーのパスワードを設定
    command:
      - start-dev # 開発モードで起動
  reverse-proxy-letsencrypt:
    container_name: reverse-proxy-letsencrypt
    image: nginx
    volumes:
      - ./execution_environment/reverse-proxy-letsencrypt/default.conf:/etc/nginx/conf.d/default.conf
      - ./execution_environment/reverse-proxy-letsencrypt/log:/var/log/nginx
      - ./execution_environment/reverse-proxy-letsencrypt/doc:/var/www/html
      - ./execution_environment/letsencrypt:/etc/nginx/conf.d/letsencrypt
    ports:
      - "80:80" # letsencrypt
      - "4443:443" 
    depends_on:
      - api
      - keycloak
  reverse-proxy-keycloak:
    container_name: reverse-proxy-keycloak
    image: nginx
    volumes:
      - ./execution_environment/reverse-proxy-keycloak/default.conf:/etc/nginx/conf.d/default.conf
      - ./execution_environment/reverse-proxy-keycloak/src:/etc/nginx/src
      - ./execution_environment/reverse-proxy-keycloak/log:/var/log/nginx
      - ./execution_environment/reverse-proxy-keycloak/doc:/var/www/html
    ports:
      - "80:80" # letsencrypt
      - "18080:8080" # api
    depends_on:
      - api
      - keycloak
  certbot:
    image: certbot/certbot:v1.7.0
    container_name: certbot
    volumes:
      - ./execution_environment/letsencrypt:/etc/letsencrypt
      - ./execution_environment/reverse-proxy/doc:/var/www/html
    command: ["--version"]